---
title: "Mini-Project 2"
author: "Hening Zheng, Jaime Pettit"
date: "October 31, 2017"
output: html_document
---


## Swing States General Votes by District

This project is so interesting and relevant to my life!

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
```

```{r, message=FALSE}
theme_swing <- function () { 
    theme(
      aspect.ratio = 0.618,
      text = element_text(family = "Avenir"),
      axis.title.x = element_text(size = 20, color = "black",
                                  margin = margin(8,0,0,0,"pt")),
      axis.title.y = element_text(size = 17, color = "black",
                                  margin = margin(0,8,0,0,"pt")),
      axis.text.x = element_text(size = 20, color = "black",
                                  margin = margin(6,0,0,0,"pt")),
      axis.text.y = element_text(size = 20, color = "black",
                                  margin = margin(0,6,0,0,"pt")),
      plot.title = element_text(face = 2, 
                                size = 30,
                                margin = margin(0,0,-25,0,"pt")),
      axis.ticks = element_blank(),
      legend.title = element_blank(),
      legend.text = element_text(size = 15, color = "black"),
      legend.position = "top",
      panel.grid.major = element_line(color = NA),
      panel.grid.minor = element_line(color = NA),
      panel.background = element_blank()
  )
}

party_by_state <- function(state_arg) {
  house_elections %>%
  filter(state == state_arg) %>%
  group_by(party) %>%
  summarize(N = n(),
            primary = sum(primary_votes),
            general = sum(general_votes)) %>%
  arrange(desc(general))
}

swing <- function(state_arg) {
  partydata <- party_by_state(state_arg) 
  winner_party <- partydata[1,]
  dem <- partydata %>% subset(party == "D")
  rep <- partydata %>% subset(party == "R")
  partydata %>% summarize(state = state_arg,
                          total_votes = sum(general),
                          winner = winner_party$party[1],
                          dem_votes = dem$general[1],
                          rep_votes = rep$general[1],
                          dem_vs_rep = dem_votes/rep_votes)
}

states <- house_elections %>% 
  select(state) %>%
  unique()
states <- states$state

top_10_swing <- lapply(states, swing) %>%
  bind_rows() %>%
  filter(abs(dem_vs_rep-1) < 0.1) %>%
  arrange(abs(dem_vs_rep-1))

swing_states <- top_10_swing$state

swing_district <- function(state_arg) {
  house_elections %>%
    filter(state == state_arg) %>%
    group_by(district) %>% 
    summarize(N = n(),
              total = sum(general_votes),
              D = sum(ifelse(party == "D", general_votes, 0))/total*100,
              R = sum(ifelse(party == "R", general_votes, 0))/total*100,
              others = 100-D-R)
}

swing_district_graph <- function(state_arg) {
  swing_district(state_arg)  %>%
    gather("party", "percentage", 4:6) %>%
    mutate(party = factor(party, levels = c("D", "R", "others"), 
                          labels = c("Democrat", "Republican", "others"))) %>%
    arrange(district) %>%
    ggplot(aes(x = district, y = percentage, fill = party)) +
    geom_bar(stat = "identity", position = position_stack(reverse = TRUE)) +
    ggtitle(label = state_arg) +
    scale_fill_manual("legend", values = c("#5DA2F5", "#F77471", "#1EB742")) +
    scale_x_discrete(name = "District",
                     labels = NULL,
                     expand=c(0, 0)) +
    scale_y_continuous(name = NULL,
                       breaks = seq(0, 100, 50),
                       labels = c("0%", "50%", "100%"),
                       expand=c(0, 0)) +
    theme_swing()
}

swing_district_plots <- lapply(swing_states, swing_district_graph)

i <- 0
while (i < length(swing_district_plots)) {
  i <- i + 1
  print(swing_district_plots[[i]])  
}

contribution_by_district <- function(state_arg, data_arg, type_arg) {
  if (data_arg == "tie") {
    data <- swing_district(state_arg) %>%
      slice(which.min(abs(D - R)))
  } else if (data_arg == "dem_adv") {
    data <- swing_district(state_arg) %>%
      slice(which.max(D))
  } else if (data_arg == "rep_adv"){
    data <- swing_district(state_arg) %>%
      slice(which.max(R))
  } 
  
  data <- house_elections %>%
    filter(state == state_arg, district %in% data$district, general_votes != 0) %>%
    select(fec_id, state, district, general_votes, party, ge_winner)
  
  colnames(data)[1] <- "cand_id"
  
  if (is.null(type_arg)) {
    contribution_type <- contributions %>%
      filter(cand_id %in% data$cand_id)
  } else {
    contribution_type <- contributions %>%
      filter(cand_id %in% data$cand_id, transaction_type == type_arg)
  }
  contribution_type %>%
    select(cand_id, transaction_amt) %>%
    group_by(cand_id) %>%
    summarize(contribution = sum(transaction_amt)) %>%
    inner_join(data, by = "cand_id")
}

contribution_graph <- function(data_arg, type_arg) {
  data <- lapply(swing_states, contribution_by_district, data_arg, type_arg) %>%
    bind_rows()
  
  parties <- data$party
  i <- 0
  while (i < length(parties)) {
    i <- i + 1
    if (parties[[i]] != "D" && parties[[i]] != "R") {
      parties[[i]] = "others"
    }
  }
  
  data %>% mutate(party = parties,
                  party = factor(party, levels = c("D", "R", "others"), 
                          labels = c("Democrat", "Republican", "others"))) %>%
    ggplot(aes(x = state, y = contribution, fill = party)) +
    geom_bar(stat = "identity", position = position_stack(reverse = TRUE)) +
    scale_fill_manual("legend", values = c("#5DA2F5", "#F77471", "#1EB742")) +
    scale_x_discrete(name = NULL,
                     limits = swing_states,
                     expand = c(0, 0)) +
    scale_y_continuous(name = "Total Contribution (million)",
                       breaks = seq(0, 10000000, 2000000),
                       labels = seq(0, 10, 2),
                       expand = c(0, 0)) +
    theme_swing() +
    theme(plot.title = element_text(face = 2, 
                                    size = 20,
                                    margin = margin(0,0,5,0,"pt"),
                                    hjust = 0.5),
          legend.position = "bottom")
}

districts <- c("tie", "dem_adv", "rep_adv")

contribution_plots <- lapply(districts, contribution_graph, NULL)

contribution_plots[[1]] +
  ggtitle(label = "Contribution Related to Candidates of \nthe Most Closely Tied District \nin Each Swing State") +
  scale_y_continuous(breaks = seq(0, 12500000, 2500000),
                     labels = seq(0, 12.5, 2.5))

contribution_plots[[2]] +
  ggtitle(label = "Contribution Related to Candidates of \nthe Most Democrat-Advantaged District \nin Each Swing State")

contribution_plots[[3]] +
  ggtitle(label = "Contribution Related to Candidates of \nthe Most Republican-Advantaged District \nin Each Swing State")

advocation_plots <- lapply(districts, contribution_graph, "24E")
opposition_plots <- lapply(districts, contribution_graph, "24A")

advocation_plots[[1]] +
  ggtitle(label = "Individual Contribution Advocating Candidates of \nthe Most Closely Tied District \nin Each Swing State") +
  scale_y_continuous(name = "Total Contribution (100k)",
                     breaks = seq(0, 2400000, 400000),
                     labels = seq(0, 24, 4))

opposition_plots[[1]] +
  ggtitle(label = "Individual Contribution Opposing Candidates of \nthe Most Closely Tied District \nin Each Swing State")

advocation_plots[[2]] +
  ggtitle(label = "Individual Contribution Advocating Candidates of \nthe Most Democrat-Advantaged District \nin Each Swing State") +
  scale_y_continuous(name = "Total Contribution (100k)",
                     breaks = seq(0, 1000000, 100000),
                     labels = seq(0, 10, 1))

opposition_plots[[2]] +
  ggtitle(label = "Individual Contribution Opposing Candidates of \nthe Most Democrat-Advantaged District \nin Each Swing State")

advocation_plots[[3]] +
  ggtitle(label = "Individual Contribution Advocating Candidates of \nthe Most Republican-Advantaged District \nin Each Swing State") +
  scale_y_continuous(name = "Total Contribution (100k)",
                     breaks = seq(0, 1000000, 200000),
                     labels = seq(0, 10, 2))

opposition_plots[[3]] +
  ggtitle(label = "Individual Contribution Opposing Candidates of \nthe Most Republican-Advantaged District \nin Each Swing State")

```
  